# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyairhealth',
                'doc_host': 'https://jinhyokh.github.io',
                'git_url': 'https://github.com/jinhyokh/pyairhealth',
                'lib_path': 'pyairhealth'},
  'syms': {'pyairhealth.core': {'pyairhealth.core.foo': ('core.html#foo', 'pyairhealth/core.py')}}}
